---
# tasks file for join_workers
# - name: checking if node already in a 

- name: checking if already is a member of k8s cluster
  stat: 
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_config

- name: joining workers in the cluster
  shell: 
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }}
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}
    {{K8S_MASTER_ADDRESS}}:{{K8S_MASTER_PORT}}
  when: kubelet_config.stat.exists == false
  