---
# tasks file for init_cluster
- name: checking if cluster already exists
  shell:
    kubectl version
  ignore_errors: true
  changed_when: false
  register: cluster_info 

- name: pulling k8s images   
  command: 
    kubeadm config images pull  
  when: cluster_info.stderr.find('was refused') > 0

- name: initialize cluster
  command:
    kubeadm init
  register: kubeadm_init
  when: cluster_info.stderr.find('was refused') > 0

- name: creating the config directory .kube
  file:
    path: ~/.kube
    state: directory

- name: linking default config file
  file:
    src: /etc/kubernetes/admin.conf
    dest: ~/.kube/config
    state: link

- name: installing pod network
  shell: kubectl apply -f {{ podnetwork_url }}
  changed_when: false

- name: saving join tokens 
  shell: kubeadm token list | cut -d ' ' -f1 | sed -n '2p'
  register: k8s_token
  changed_when: false

- name: CA Hash
  shell: openssl x509 -pubkey -in /etc/kubernetes/pki/ca.crt | openssl rsa -pubin -outform der 2>/dev/null | openssl dgst -sha256 -hex | sed 's/^.* //'
  register: k8s_master_ca_hash

- name: adding the join token and ca hash in the dummy host
  add_host:
    name: "K8S_TOKEN_HOLDER"
    token: "{{ k8s_token.stdout }}"
    hash: "{{ k8s_master_ca_hash.stdout }}"