---
# tasks file for configure_node
- name: Load kernel modules needed
  copy:
    src: ./files/k8s.conf
    dest: /etc/modules-load.d/k8s.conf
  notify: restart

- name: Configure ip tables/netfilter
  copy:
    src: files/netfilter-k8s.conf
    dest: /etc/sysctl.d/k8s.conf
  notify: restart

- name: Enabled ip forwarding
  lineinfile:
    path: /etc/sysctl.conf
    insertafter: "#net.ipv4.ip_forward=1"
    line: "net.ipv4.ip_forward=1"
  notify: restart

- name: Disable swap
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  notify: restart

- name: Enable cgroup params on boot
  replace:
    path: /boot/firmware/cmdline.txt    
    regexp: '^([\w](?!.*\b{{ item }}\b).*)$'
    replace: '\1 {{ item }}'
  with_items:
    - "cgroup_enable=cpuset"
    - "cgroup_memory=1"
    - "cgroup_enable=memory"
  when: ansible_facts['architecture'] == "aarch64"
  notify: restart  
